from pathlib import Path

root = Path(__name__).resolve().parent
icon_path = root.joinpath("ziton/resources/icons")
gif_path = root.joinpath("ziton/resources/gifs")

# ICONS
ADD = icon_path.joinpath("add.png")
CSV = icon_path.joinpath("csv.png")
HASKELL = icon_path.joinpath("haskell.png")
PNG = icon_path.joinpath("png.png")
TEXT_LINES = icon_path.joinpath("text-lines.png")
APPLICATION = icon_path.joinpath("application.png")
DATABASE = icon_path.joinpath("database.png")
HTML = icon_path.joinpath("html.png")
PYTHON = icon_path.joinpath("python.png")
TRASH = icon_path.joinpath("trash.png")
ARCHIVE = icon_path.joinpath("archive.png")
FOLDER = icon_path.joinpath("folder.png")
JAVA = icon_path.joinpath("java.png")
RAR = icon_path.joinpath("rar.png")
UNKNOWN = icon_path.joinpath("unknown.png")
AUDIO = icon_path.joinpath("audio.png")
FONT = icon_path.joinpath("font.png")
JPG = icon_path.joinpath("jpg.png")
REMOVE = icon_path.joinpath("remove.png")
VIDEO_PLAYER = icon_path.joinpath("video-player.png")
C = icon_path.joinpath("c.png")
GIF = icon_path.joinpath("gif.png")
JSON_FILE = icon_path.joinpath("json-file.png")
RUBY = icon_path.joinpath("ruby.png")
XML = icon_path.joinpath("xml.png")
CPP = icon_path.joinpath("cpp.png")
GNU_BASH = icon_path.joinpath("gnu-bash.png")
PDF = icon_path.joinpath("pdf.png")
TAR = icon_path.joinpath("tar.png")
ZIP = icon_path.joinpath("zip.png")
CSS = icon_path.joinpath("css.png")
HARD_DRIVE = icon_path.joinpath("hard-drive.png")
PICTURE = icon_path.joinpath("picture.png")
TEX_FILE_FORMAT = icon_path.joinpath("tex-file-format.png")
LOGO = icon_path.joinpath("logo.png")
LOGOUT = icon_path.joinpath("logout.png")
PREFERENCE = icon_path.joinpath("preference.png")
UPPERCASE = icon_path.joinpath("uppercase.png")
# GIFS
SPINNER = gif_path.joinpath("loading.gif")
